### ISSUE TITLE
订阅时发生错误

### ISSUE THREAD

**Issue by guyingd** [amtoaer/bing-bong#2]
unexpected fault address 0x808085a175a75
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x808085a175a75 pc=0x4671f0]

goroutine 42 [running]:
runtime.throw({0xa67d8b?, 0x85d54c?})
        /usr/lib/go-1.18/src/runtime/panic.go:992 +0x50 fp=0x40000d10e0 sp=0x40000d10b0 pc=0x43a980
runtime.sigpanic()
        /usr/lib/go-1.18/src/runtime/signal_unix.go:825 +0x1a4 fp=0x40000d1110 sp=0x40000d10e0 pc=0x450e94
aeshashbody()
        /usr/lib/go-1.18/src/runtime/asm_arm64.s:874 +0x2d0 fp=0x40000d1120 sp=0x40000d1120 pc=0x4671f0
runtime.mapiternext(0x4000298040)
        /usr/lib/go-1.18/src/runtime/map.go:934 +0x2c4 fp=0x40000d1190 sp=0x40000d1120 pc=0x415fb4
runtime.mapiterinit(0x40000d1218?, 0x411644?, 0x40000d12b8?)
        /usr/lib/go-1.18/src/runtime/map.go:861 +0x2f4 fp=0x40000d11c0 sp=0x40000d1190 pc=0x415cb4
reflect.mapiterinit(0x40000d1288?, 0x200000003?, 0x40000d1278?)
        /usr/lib/go-1.18/src/runtime/map.go:1373 +0x20 fp=0x40000d11f0 sp=0x40000d11c0 pc=0x4640d0
github.com/modern-go/reflect2.(*UnsafeMapType).UnsafeIterate(...)
        /root/go/pkg/mod/github.com/modern-go/reflect2@v1.0.2-0.20210109003243-333559e1834b/unsafe_map.go:112
github.com/json-iterator/go.(*mapEncoder).Encode(0x4000284390, 0x400028a1f0, 0x4000290000)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_map.go:257 +0x238 fp=0x40000d12b0 sp=0x40000d11f0 pc=0x6aceb8
github.com/json-iterator/go.(*structFieldEncoder).Encode(0x40002844e0, 0x98f404?, 0x4000290000)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:110 +0x58 fp=0x40000d1330 sp=0x40000d12b0 pc=0x6ba178
github.com/json-iterator/go.(*structEncoder).Encode(0x4000284570, 0x9b7540?, 0x4000290000)
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect_struct_encoder.go:158 +0x708 fp=0x40000d1420 sp=0x40000d1330 pc=0x6baaf8
github.com/json-iterator/go.(*Stream).WriteVal(0x4000290000, {0xa0f020, 0x400028a1e0})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/reflect.go:98 +0x174 fp=0x40000d14a0 sp=0x40000d1420 pc=0x6a5094
github.com/json-iterator/go.(*frozenConfig).Marshal(0x40000c0aa0, {0xa0f020, 0x400028a1e0})
        /root/go/pkg/mod/github.com/json-iterator/go@v1.1.11/config.go:299 +0x88 fp=0x40000d1540 sp=0x40000d14a0 pc=0x69c1b8
github.com/wdvxdr1123/ZeroBot/driver.(*WSClient).CallApi(0x400022ae70, {{0xa70376?, 0x40000be000?}, 0x40002852c0, 0x40000d1818?})
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/driver/websocket.go:120 +0x124 fp=0x40000d17d0 sp=0x40000d1540 pc=0x8ab484
github.com/wdvxdr1123/ZeroBot.(*Ctx).CallAction(0x9e7940?, {0xa70376, 0xe}, 0x7?)
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/api.go:35 +0x5c fp=0x40000d19e0 sp=0x40000d17d0 pc=0x891eac
github.com/wdvxdr1123/ZeroBot.(*Ctx).SendGroupMessage(0x0?, 0x0?, {0x9b72c0?, 0xb41288})
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/api.go:48 +0x100 fp=0x40000d1ca0 sp=0x40000d19e0 pc=0x8921c0
github.com/wdvxdr1123/ZeroBot.(*Ctx).Send(0x36e165cd?, {0x9b72c0?, 0xb41288?})
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/context.go:90 +0x40 fp=0x40000d1cd0 sp=0x40000d1ca0 pc=0x898230
github.com/amtoaer/bing-bong/client.(*QQ).HandleEvent.func1(0x40002849f0)
        /home/机器人/插件/订阅/bing-bong/client/qq.go:105 +0x330 fp=0x40000d1e20 sp=0x40000d1cd0 pc=0x8ad940
github.com/wdvxdr1123/ZeroBot.processEvent({0x400028f200, 0x1df, 0x200}, {0xb430a8?, 0x400022ae70})
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/bot.go:105 +0x63c fp=0x40000d1f90 sp=0x40000d1e20 pc=0x8963dc
github.com/wdvxdr1123/ZeroBot/driver.(*WSClient).Listen.func1()
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/driver/websocket.go:105 +0x44 fp=0x40000d1fd0 sp=0x40000d1f90 pc=0x8ab324
runtime.goexit()
        /usr/lib/go-1.18/src/runtime/asm_arm64.s:1259 +0x4 fp=0x40000d1fd0 sp=0x40000d1fd0 pc=0x469c94
created by github.com/wdvxdr1123/ZeroBot/driver.(*WSClient).Listen
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/driver/websocket.go:105 +0x89c

goroutine 1 [select (no cases)]:
github.com/amtoaer/bing-bong/client.(*QQ).HandleEvent(0x40001d7d60?, 0x40001d7d60)
        /home/机器人/插件/订阅/bing-bong/client/qq.go:219 +0x518
main.main()
        /home/机器人/插件/订阅/bing-bong/main.go:34 +0x168

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7c03a273d8, 0x72)
        /usr/lib/go-1.18/src/runtime/netpoll.go:302 +0xa4
internal/poll.(*pollDesc).wait(0x4000140800?, 0x400022e000?, 0x0)
        /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:83 +0x2c
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go-1.18/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0x4000140800, {0x400022e000, 0x1000, 0x1000})
        /usr/lib/go-1.18/src/internal/poll/fd_unix.go:167 +0x1ec
net.(*netFD).Read(0x4000140800, {0x400022e000?, 0x40000c76a8?, 0x44abe0?})
        /usr/lib/go-1.18/src/net/fd_posix.go:55 +0x2c
net.(*conn).Read(0x40000b6900, {0x400022e000?, 0x0?, 0xf8e0c8?})
        /usr/lib/go-1.18/src/net/net.go:183 +0x38
bufio.(*Reader).fill(0x40000b88a0)
        /usr/lib/go-1.18/src/bufio/bufio.go:106 +0x100
bufio.(*Reader).Peek(0x40000b88a0, 0x2)
        /usr/lib/go-1.18/src/bufio/bufio.go:144 +0x6c
github.com/gorilla/websocket.(*Conn).read(0x40000fe580, 0x413618?)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370 +0x2c
github.com/gorilla/websocket.(*Conn).advanceFrame(0x40000fe580)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798 +0x68
github.com/gorilla/websocket.(*Conn).NextReader(0x40000fe580)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980 +0xa8
github.com/gorilla/websocket.(*Conn).ReadMessage(0x400028f200?)
        /root/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1064 +0x20
github.com/wdvxdr1123/ZeroBot/driver.(*WSClient).Listen(0x400022ae70, 0xaad800)
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/driver/websocket.go:78 +0x40
created by github.com/wdvxdr1123/ZeroBot.Run
        /root/go/pkg/mod/github.com/wdvxdr1123/!zero!bot@v1.2.2/bot.go:46 +0x158

goroutine 5 [select]:
database/sql.(*DB).connectionOpener(0x40003041a0, {0xb470a8, 0x40000300c0})
        /usr/lib/go-1.18/src/database/sql/sql.go:1226 +0x84
created by database/sql.OpenDB
        /usr/lib/go-1.18/src/database/sql/sql.go:794 +0x188

goroutine 6 [chan receive]:
github.com/amtoaer/bing-bong/internal.CheckMessage(0x40001d7d60)
        /home/机器人/插件/订阅/bing-bong/internal/rss.go:31 +0x88
created by main.main
        /home/机器人/插件/订阅/bing-bong/main.go:33 +0x150
exit status 2

**Comment by guyingd** [comment]
无法订阅，包括你的https://blog.allwens.work/atom.xml

**Comment by amtoaer** [comment]
抱歉最近工作繁忙，现在才回复。我刚刚在最新的 archlinux 上成功运行了最新的预构建版本，方便的话可以先尝试使用预构建版本。
看错误信息似乎是上游的机器人框架报的错，给您两个大致的排查方向：
1. go 1.18变更较大，可先尝试使用 go 1.17编译，观察问题是否仍然存在。
2. 这似乎是机器人框架发送信息时出现的异常，可以试试不订阅，单独发送 /帮助 观察问题是否仍然存在。出现问题时检查go-cqhttp是否正常，是否有某些提示信息。

**Comment by amtoaer** [comment]
@guyingd 你好，刚刚我成功复现了类似的报错，问题是使用 go 1.19 编译，换用 go 1.17 重新编译后正常运行，可作参考。
